/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as HabitosIndexRouteImport } from './routes/habitos.index'
import { Route as HabitosComoFuncionamRouteImport } from './routes/habitos.como-funcionam'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitosIndexRoute = HabitosIndexRouteImport.update({
  id: '/habitos/',
  path: '/habitos/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitosComoFuncionamRoute = HabitosComoFuncionamRouteImport.update({
  id: '/habitos/como-funcionam',
  path: '/habitos/como-funcionam',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entrar': typeof EntrarRoute
  '/estatisticas': typeof EstatisticasRoute
  '/planejamento': typeof PlanejamentoRoute
  '/tarefas': typeof TarefasRoute
  '/habitos/como-funcionam': typeof HabitosComoFuncionamRoute
  '/habitos/': typeof HabitosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entrar': typeof EntrarRoute
  '/estatisticas': typeof EstatisticasRoute
  '/planejamento': typeof PlanejamentoRoute
  '/tarefas': typeof TarefasRoute
  '/habitos/como-funcionam': typeof HabitosComoFuncionamRoute
  '/habitos': typeof HabitosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/entrar': typeof EntrarRoute
  '/estatisticas': typeof EstatisticasRoute
  '/planejamento': typeof PlanejamentoRoute
  '/tarefas': typeof TarefasRoute
  '/habitos/como-funcionam': typeof HabitosComoFuncionamRoute
  '/habitos/': typeof HabitosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/entrar'
    | '/estatisticas'
    | '/planejamento'
    | '/tarefas'
    | '/habitos/como-funcionam'
    | '/habitos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/entrar'
    | '/estatisticas'
    | '/planejamento'
    | '/tarefas'
    | '/habitos/como-funcionam'
    | '/habitos'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/entrar'
    | '/estatisticas'
    | '/planejamento'
    | '/tarefas'
    | '/habitos/como-funcionam'
    | '/habitos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EntrarRoute: typeof EntrarRoute
  EstatisticasRoute: typeof EstatisticasRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  TarefasRoute: typeof TarefasRoute
  HabitosComoFuncionamRoute: typeof HabitosComoFuncionamRoute
  HabitosIndexRoute: typeof HabitosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitos/': {
      id: '/habitos/'
      path: '/habitos'
      fullPath: '/habitos/'
      preLoaderRoute: typeof HabitosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitos/como-funcionam': {
      id: '/habitos/como-funcionam'
      path: '/habitos/como-funcionam'
      fullPath: '/habitos/como-funcionam'
      preLoaderRoute: typeof HabitosComoFuncionamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EntrarRoute: EntrarRoute,
  EstatisticasRoute: EstatisticasRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  TarefasRoute: TarefasRoute,
  HabitosComoFuncionamRoute: HabitosComoFuncionamRoute,
  HabitosIndexRoute: HabitosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
